package com.prajwalpawar.fiscus.ui.theme

import androidx.compose.ui.graphics.Color

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

// --- MONOCHROME ---
val MonochromeLightColorScheme = lightColorScheme(
    primary = Color(0xFF1A1A1A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFEAEAEA),
    onPrimaryContainer = Color(0xFF1A1A1A),
    secondary = Color(0xFF4D4D4D),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE0E0E0),
    onSecondaryContainer = Color(0xFF1A1A1A),
    tertiary = Color(0xFF333333),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD6D6D6),
    onTertiaryContainer = Color(0xFF1A1A1A),
    error = Color(0xFFB00020),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFCD8DF),
    onErrorContainer = Color(0xFF3D000A),
    background = Color(0xFFFCFCFC),
    onBackground = Color(0xFF1A1A1A),
    surface = Color(0xFFFCFCFC),
    onSurface = Color(0xFF1A1A1A),
    surfaceVariant = Color(0xFFE0E0E0),
    onSurfaceVariant = Color(0xFF4D4D4D),
    outline = Color(0xFF757575),
    outlineVariant = Color(0xFFBDBDBD),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF333333),
    inverseOnSurface = Color(0xFFF5F5F5),
    inversePrimary = Color(0xFFEAEAEA),
    surfaceDim = Color(0xFFD6D6D6),
    surfaceBright = Color(0xFFFAFAFA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F4F4),
    surfaceContainer = Color(0xFFEAEAEA),
    surfaceContainerHigh = Color(0xFFE0E0E0),
    surfaceContainerHighest = Color(0xFFD6D6D6),
    surfaceTint = Color(0xFF1A1A1A)
)

val MonochromeDarkColorScheme = darkColorScheme(
    primary = Color(0xFFE5E5E5),
    onPrimary = Color(0xFF1A1A1A),
    primaryContainer = Color(0xFF333333),
    onPrimaryContainer = Color(0xFFE5E5E5),
    secondary = Color(0xFFB3B3B3),
    onSecondary = Color(0xFF1A1A1A),
    secondaryContainer = Color(0xFF404040),
    onSecondaryContainer = Color(0xFFE5E5E5),
    tertiary = Color(0xFFCCCCCC),
    onTertiary = Color(0xFF1A1A1A),
    tertiaryContainer = Color(0xFF4D4D4D),
    onTertiaryContainer = Color(0xFFE5E5E5),
    error = Color(0xFFCF6679),
    onError = Color(0xFF1A1A1A),
    errorContainer = Color(0xFFB00020),
    onErrorContainer = Color(0xFFFCD8DF),
    background = Color(0xFF121212),
    onBackground = Color(0xFFE5E5E5),
    surface = Color(0xFF121212),
    onSurface = Color(0xFFE5E5E5),
    surfaceVariant = Color(0xFF404040),
    onSurfaceVariant = Color(0xFFB3B3B3),
    outline = Color(0xFF8C8C8C),
    outlineVariant = Color(0xFF404040),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE5E5E5),
    inverseOnSurface = Color(0xFF333333),
    inversePrimary = Color(0xFF1A1A1A),
    surfaceDim = Color(0xFF1A1A1A),
    surfaceBright = Color(0xFF3A3A3A),
    surfaceContainerLowest = Color(0xFF0A0A0A),
    surfaceContainerLow = Color(0xFF1A1A1A),
    surfaceContainer = Color(0xFF242424),
    surfaceContainerHigh = Color(0xFF2E2E2E),
    surfaceContainerHighest = Color(0xFF383838),
    surfaceTint = Color(0xFFE5E5E5)
)